version: "3.9"
services:

  trainer:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.main
      target: trainer
    runtime: nvidia
    depends_on:
      - redis
    profiles: ["training"]

  worker:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.main
      target: worker
    depends_on:
      - redis
    profiles: ["training"]

  sidecar:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.sidecar
    ports:
      - "8000:5000"
    depends_on:
      - redis
    profiles: ["training", "db"]

  redis:
    image: "redis:7.0-rc1"
    command: sh -c "rm -f /data/dump.rdb && redis-server"
    ports:
      - "6379:6379"
    profiles: ["training", "db"]
