version: "3.9"
services:

  trainer:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.main
      target: trainer
    runtime: nvidia
    depends_on:
      - redis
    profiles: ["training"]
    volumes:
      - models:/code/models:rw
      - tb:/code/summaries:rw

  worker:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.main
      target: worker
    depends_on:
      - redis
    profiles: ["training"]
    scale: 4

  redis:
    image: "redis:7.0-rc1"
    # command: sh -c "rm -f /data/dump.rdb && redis-server"
    ports:
      - "6379:6379"
    profiles: ["training", "db"]

  sidecar:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.sidecar
    ports:
      - "8000:5000"
    depends_on:
      - redis
    profiles: ["training", "db"]

  tensorboard:
    image: tensorflow/tensorflow:2.8.0-gpu
    command: ["bash", "-c", "tensorboard", "--logdir", "/mnt"]
    volumes:
      - tb:/mnt:ro
    profiles: ["training"]

volumes:
  tb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./summaries"
  models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./models"
