version: "3.9"
services:

  trainer:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.main
      target: trainer
    runtime: nvidia
    depends_on:
      - redis
    profiles: ["training"]
    volumes:
      - models:/code/models:rw
      - tb:/code/summaries:rw

  worker:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.main
      target: worker
    depends_on:
      - redis
      - trainer
    profiles: ["training"]
    scale: 3

  redis:
    image: "redis:7.0-rc1"
    command: sh -c "cd /mnt && redis-server"
    ports: ["6379:6379"]
    profiles: ["training", "data", "db"]
    volumes:
      - db:/mnt:rw

  # sidecar:
  #   build:
  #     context: .
  #     dockerfile: dockerfiles/Dockerfile.sidecar
  #   ports: ["8000:5000"]
  #   depends_on:
  #     - redis
  #   profiles: ["training", "data", "db"]
  #
  # tensorboard:
  #   image: tensorflow/tensorflow:2.8.0-gpu
  #   command: ["tensorboard", "--logdir", "/mnt", "--bind_all"]
  #   volumes:
  #     - tb:/mnt:ro
  #   profiles: ["training", "data"]
  #   ports: ["6006:6006"]

#
#
##
###
#####
volumes:
  tb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./data/summaries"
  models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./data/models"
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./data/db"
