version: "3.9"
services:

  worker:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.main
    runtime: nvidia

  sidecar:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.sidecar
    ports:
      - "8000:5000"

  redis:
    image: "redis:7.0-rc"
