# syntax=docker/dockerfile:1
FROM python:3.9-alpine
ENV FLASK_APP=tools/sidecar_app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV PYTHONPATH=.
RUN apk add --no-cache gcc musl-dev linux-headers
WORKDIR /code
COPY dockerfiles/requirements.sidecar.txt .
RUN pip install -r requirements.sidecar.txt
COPY . .
EXPOSE 5000
CMD ["flask", "run"]
